### ISSUE TITLE
scan[1] data is missing 

### ISSUE THREAD

**Issue by bilalah21** [KumarRobotics/velodyne_puck#5]
In VelodynePuckSweep.msg 

"The 0th scan is at the bottom
VelodynePuckScan[16] scans"

If you read messages from bottom. The second last msg points [] array is empty.
Which if (0th scan at bottom as mentioned) is true then that will make it scan[1] for the laser pointing at 1 degree.

**Comment by ke-sun** [comment]
I don't quite understand the problem you point out. Could you please be more specific?

**Comment by bilalah21** [comment]
Below i am attaching the output of velodyne_sweep topic of just one seq. As each sweep will have 16 points array corresponding to the each laser ring id. 
`
```
header:
seq: 267
stamp: 
secs: 1511861396
nsecs: 220682621
frame_id: 
scans: 
```
 
    altitude: 0.0
    points: 
      - 
        time: 0.0
        x: 2.91709453685
        y: -0.00291709550921
        z: -0.78163351621
        azimuth: 0.00069813168
        distance: 3.02
        intensity: 1.0
      - 
        time: 3628.80004883
        x: 8.15783066996
        y: -1.90149884569
        z: 2.24447875913
        azimuth: 0.228583583662
        distance: 8.672
        intensity: 10.0
      -
     ........  // Laser ring 15 points measurements Continues normally
     ........
 
    altitude: 0.0
    points: 
      - 
        time: 3573.50390625
        x: 8.28965978454
        y: -1.89729895208
        z: 2.27864287308
        azimuth: 0.225180191722
        distance: 8.804
        intensity: 5.0
      - 
        time: 3628.80004883
        x: 8.15783066996
        y: -1.90149884569
        z: 2.24447875913
        azimuth: 0.228583583662
        distance: 8.672
        intensity: 10.0
      - 
     
     ......  // Laser ring 14 measurements continues normally
	 ...... //skipping to last two measurements of altitude points
	 ......
	 ......
//Below Here this Scan which is second last from the bottom meaning Scan for Laser Ring ID 1 is empty. The points array is empty.

    

```
altitude: 0.0       
    points: []
```

    altitude: 0.0        //laser ring 0 measurement at the bottom continues normally
    points: 
      - 
        time: 3573.50390625
        x: 8.28965978454
        y: -1.89729895208
        z: 2.27864287308
        azimuth: 0.225180191722
        distance: 8.804
        intensity: 5.0
      - 
        time: 3628.80004883
        x: 8.15783066996
        y: -1.90149884569
        z: 2.24447875913
        azimuth: 0.228583583662
        distance: 8.672
        intensity: 10.0
      - `
